from __future__ import annotations

from typing import Any


def _ev(
    source_id: str,
    claim_key: str,
    severity: str,
    confidence: float = 0.9,
    source_name: str | None = None,
) -> dict[str, Any]:
    return {
        "source_id": source_id,
        "source_name": source_name or source_id,
        "tier": "tier1",
        "category": "advisory",
        "claim_key": claim_key,
        "claim_text": f"{claim_key} indicates {severity}",
        "event_time": "2026-08-17T00:00:00Z",
        "fetched_at": "2026-08-17T00:00:00Z",
        "severity": severity,
        "confidence": confidence,
        "extraction_note": "fixture",
        "event_id": f"{source_id}:{claim_key}:{severity}",
    }


def _case(
    name: str,
    clearance: str,
    truth_critical: bool,
    truth_severity_score: float,
    evidence: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "name": name,
        "user_input": {
            "residence_country": "US",
            "clearance_level": clearance,
            "agency": "DIA",
            "destination_country": "FixtureLand",
            "destination_city": "FixtureCity",
            "long_report": False,
            "nrt_enabled": False,
            "strict_country_match": True,
        },
        "truth": {
            "critical_environment": truth_critical,
            "true_severity_score": truth_severity_score,
        },
        "evidence": evidence,
    }


def _triplet(claim_key: str, severities: tuple[str, str, str], conf: tuple[float, float, float] | None = None) -> list[dict[str, Any]]:
    c = conf or (0.9, 0.88, 0.87)
    return [
        _ev("s1", claim_key, severities[0], c[0]),
        _ev("s2", claim_key, severities[1], c[1]),
        _ev("s3", claim_key, severities[2], c[2]),
    ]


def _build_case(
    name: str,
    clearance: str,
    truth_critical: bool,
    truth_severity_score: float,
    official: tuple[str, str, str],
    unrest: tuple[str, str, str],
    crime: tuple[str, str, str],
    terror: tuple[str, str, str],
    health: tuple[str, str, str],
    infra: tuple[str, str, str],
) -> dict[str, Any]:
    evidence: list[dict[str, Any]] = []
    evidence.extend(_triplet("official_advisory", official))
    evidence.extend(_triplet("political_unrest", unrest))
    evidence.extend(_triplet("violent_crime_kidnapping", crime))
    evidence.extend(_triplet("terrorism_organized_violence", terror))
    evidence.extend(_triplet("health_bio_environmental", health))
    evidence.extend(_triplet("infrastructure_transport", infra))
    return _case(name, clearance, truth_critical, truth_severity_score, evidence)


VALIDATION_CASES: list[dict[str, Any]] = [
    _build_case("critical_consensus_a", "TS/SCI w CIP", True, 96.0,
                ("critical", "critical", "critical"),
                ("elevated", "high", "elevated"),
                ("critical", "critical", "high"),
                ("critical", "critical", "high"),
                ("high", "high", "elevated"),
                ("high", "elevated", "high")),
    _build_case("critical_consensus_b", "TS/SCI", True, 93.0,
                ("critical", "critical", "critical"),
                ("high", "high", "elevated"),
                ("critical", "high", "high"),
                ("critical", "high", "critical"),
                ("elevated", "high", "elevated"),
                ("high", "high", "high")),
    _build_case("critical_mixed_low_sources", "TS", True, 88.0,
                ("critical", "critical", "critical"),
                ("low", "elevated", "low"),
                ("critical", "low", "critical"),
                ("critical", "low", "low"),
                ("low", "low", "elevated"),
                ("low", "low", "low")),
    _build_case("critical_single_vector", "Secret", True, 84.0,
                ("critical", "critical", "critical"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("critical", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("high_noncritical_consensus_a", "Secret", False, 72.0,
                ("high", "high", "high"),
                ("elevated", "high", "elevated"),
                ("high", "high", "elevated"),
                ("high", "elevated", "high"),
                ("elevated", "elevated", "elevated"),
                ("high", "elevated", "high")),
    _build_case("high_noncritical_consensus_b", "TS", False, 69.0,
                ("high", "high", "high"),
                ("high", "elevated", "elevated"),
                ("elevated", "high", "elevated"),
                ("high", "high", "elevated"),
                ("low", "elevated", "elevated"),
                ("high", "high", "elevated")),
    _build_case("elevated_consensus_a", "Public Trust", False, 52.0,
                ("elevated", "elevated", "elevated"),
                ("elevated", "low", "elevated"),
                ("low", "elevated", "low"),
                ("low", "low", "elevated"),
                ("low", "low", "low"),
                ("elevated", "low", "low")),
    _build_case("elevated_consensus_b", "Secret", False, 48.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "elevated"),
                ("elevated", "low", "low"),
                ("low", "low", "low"),
                ("low", "elevated", "low"),
                ("low", "low", "low")),
    _build_case("elevated_low_mix", "Secret", False, 45.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "elevated")),
    _build_case("moderate_noncritical_a", "Public Trust", False, 37.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("moderate_noncritical_b", "Public Trust", False, 34.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("elevated", "low", "low")),
    _build_case("low_consensus_a", "Public Trust", False, 15.0,
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("low_consensus_b", "Public Trust", False, 12.0,
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("red_team_stale_like_signal", "TS", False, 31.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "elevated"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("red_team_disagreement_a", "TS/SCI", True, 82.0,
                ("critical", "critical", "critical"),
                ("elevated", "low", "low"),
                ("critical", "low", "low"),
                ("critical", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("red_team_disagreement_b", "TS/SCI", True, 80.0,
                ("critical", "critical", "critical"),
                ("high", "low", "low"),
                ("high", "low", "critical"),
                ("critical", "low", "low"),
                ("elevated", "low", "low"),
                ("low", "low", "low")),
    _build_case("red_team_borderline_high", "TS", False, 64.0,
                ("high", "high", "high"),
                ("elevated", "elevated", "low"),
                ("high", "elevated", "low"),
                ("high", "low", "low"),
                ("low", "low", "low"),
                ("elevated", "low", "low")),
    _build_case("red_team_borderline_elevated", "Secret", False, 44.0,
                ("elevated", "elevated", "elevated"),
                ("elevated", "low", "low"),
                ("elevated", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("regional_instability_health_a", "Public Trust", False, 41.0,
                ("elevated", "elevated", "elevated"),
                ("elevated", "elevated", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("high", "elevated", "low"),
                ("low", "low", "low")),
    _build_case("regional_instability_health_b", "Public Trust", False, 46.0,
                ("elevated", "elevated", "elevated"),
                ("elevated", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("high", "high", "elevated"),
                ("elevated", "low", "low")),
    _build_case("infrastructure_dominant", "Public Trust", False, 38.0,
                ("elevated", "elevated", "elevated"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("high", "elevated", "high")),
    _build_case("terrorism_concentrated", "TS", True, 90.0,
                ("critical", "critical", "critical"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("critical", "critical", "high"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("kidnapping_concentrated", "TS/SCI", True, 89.0,
                ("critical", "critical", "critical"),
                ("low", "low", "low"),
                ("critical", "critical", "high"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
    _build_case("low_with_one_noisy_high", "Public Trust", False, 20.0,
                ("low", "low", "low"),
                ("low", "low", "high"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low"),
                ("low", "low", "low")),
]
